require'civ':grequire()
grequire'motion'

test('distance', nil, function()
  assertEq(3, decDistance(1, 4))
  assertEq(2, decDistance(5, 1))
  assertEq(5, decDistance(5, 5))
end)

test('wordKind', nil, function()
  assertEq('let', wordKind('a'))
  assertEq('()',  wordKind('('))
  assertEq('()',  wordKind(')'))
  assertEq('sym', wordKind('+'))
end)

test('forword', nil, function()
  assertEq(3, forword('a bcd'))
  assertEq(3, forword('  bcd'))
  assertEq(2, forword(' bcd'))
  assertEq(3, forword('--bcd'))
  assertEq(2, forword('a+ bcd'))
  assertEq(5, forword('+12 +de', 2))
end)

test('backword', nil, function()
  assertEq(3,   backword('a bcd', 4))
  assertEq(3,   backword('  bcd', 4))
  assertEq(nil, backword('  bcd', 3))
end)

test('findBack', nil, function()
  assertEq({7, 8},   {findBack('12 45 12 ', '12')})
  assertEq({1, 2},   {findBack('12 45 12 ', '12', 6)})
end)
